config/routes.rb
Rails.application.routes.draw do
  resources :perfil

  devise_for :users
  resources :answers
  resources :questions
  

  root to: 'questions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  extend FriendlyId
  belongs_to :user
  has_many :question
  belongs_to :category

  friendly_id :category_id

  def answers
     @answers = Answer.where(question: self).count
  end

  def self.search(s)
     where("title LIKE ?", "%#{s}%")
     where("description LIKE ?", "%#{s}%")
    
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_question,  only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    if current_user && current_user.perfil.nil?
      redirect_to perfil_index_path
    end
    
    if params[:query].present?
      @questions = Question.search params[:query]
    else
      @questions = Question.all    
    end
  end


  # GET /questions/1
  # GET /questions/1.json
  def show
      @answers = Answer.where(question: @question)
      @answer = Answer.new()
  end

  # GET /questions/new
  def new
    @question = Question.new
  end



  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render  :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end



  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def answer_create
    question = params[:question]
    @answer = current_user.answer.new(answer_params)
    respond_to do |format|
      if @answer.save
        format.html { redirect_to :return_to, notice: 'Answer was successfully created.' }
        format.json { redirect_to "question/:question", status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :description, :user_id, :category_id)
    end

    def answer_params
      params.require(:answer).permit(:content, :question_id, :user_id)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for @question, :html => { :class => "form-horizontal question" } do |f| %>

<div class="page-header">
  <div class="row">
    <div class="col-sm-8">
      <h1><%= f.text_field :title, :class => 'form-control', placeholder: "Your Question" %></h1>
    </div>

  </div>
</div>
  <% if @question.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">


    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <div class="col-lg-12">
      <%= f.text_area :description, :class => 'form-control', rows: "12", placeholder: "La la la!" %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <div class="col-lg-12">

      <%= f.select_tag :category_id, options_for_select(@categories.map{|k | [k.name.capitalize, k.id]}), :class => 'form-control', rows: "12", placeholder: "La la la!" %>
    </div>
    <%=f.error_span(:description) %>
  </div>


    <%= f.hidden_field :user_id, :class => 'form-control', value: current_user.id %>


  <div class="form-group">
    <div class="col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                questions_path, :class => 'btn' %>
    </div>
  </div>

<% end %>

app/views/questions/_form_answer.html.erb
<%= form_for @answer, :html => { :class => "form-horizontal answer col-lg-offset-4 col-lg-8" } do |f| %>
  <div class="page-header">
    <h4><strong>Ask the <%= @question.user.email %>`s question!</strong></h4>
  </div>


  <div class="form-group">
    <div class="col-lg-12">
      <%= f.text_area :content, :class => 'form-control', rows: "5" %>
    </div>
    <%=f.error_span(:content) %>
  </div>

      <%= f.hidden_field :question_id, :class => 'form-control', value: @question.id %>
      <%= f.hidden_field :user_id, :class => 'form-control', value: if current_user then  current_user.id end %>



  <div class="form-group">
    <div class="col-lg-12 text-right">
      <%= f.submit "Answer this question", :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                answers_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/questions/_search_form.html.erb
  <div class="jumbotron text-center">
    <h1>What are you looking for?</h1>
<hr>
  <div class="row">
    <div class="col-sm-offset-3 col-sm-6">
      <%= form_for questions_path, method: :get, class: "form-horizontal" do | q |%>
          <div class="form-group">
            <%= q.text_field_tag :query, nil , placeholder: "Lorem ipsum dolor", class: "form-control" %>
          </div>
          
            <%= q.submit class: "btn btn-primary", value: "search" %>
          
      <% end %>
    </div>
</div>

app/views/questions/edit.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
            question_path(question_path),
            :method => :delete,
            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
            :class => 'btn btn-xs btn-danger' %>
<%= render :partial => 'form' %>

app/views/questions/index.html.erb
<%- model_class = Question -%>

<div class="page-header">
  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_question_path,
              :class => 'btn btn-primary btn-lg pull-right' %>

  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>

</div>

    <% @questions.each do |question| %>
      <div class="panel">
        <div class="card-body">
          <div class="panel-heading">
            <div class="row">
            <div class="col-sm-8">
            <h3 class=""><%= link_to question.title, question_path(question) %></h3>
            </div>
            <div class="col-sm-4 text-center">
           <small>answers: </small> <h3><%= question.answers %></h3>
            </div>
            </div>
          </div>
          <div class="panel-footer">
            <span><small>By: <%= question.user.username %> <%= question.updated_at.strftime(" on %m/%b/%Y") %></small></span>
            <%= if current_user == question.user then link_to t('.edit', :default => t("helpers.links.edit")), edit_question_path(question), class: "pull-right btn-xs btn-default" end%>
          </div>
        </div>


      </div>

    <% end %>

app/views/questions/new.html.erb
<%- model_class = Question -%>
<spam class="">
  <small><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></small>
</span>
<%= render :partial => 'form' %>

app/views/questions/search.html.erb
<%- model_class = Question -%>

<div class="page-header">
  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_question_path,
              :class => 'btn btn-primary btn-lg pull-right' %>

  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>

</div>

    <% @questions.each do |question| %>
      <div class="panel">
        <div class="card-body">
          <div class="panel-heading">
            <h3 class=""><%= link_to question.title, question_path(question) %></h3>
          </div>
          <div class="panel-footer">
            <span><small>By: <%= question.user.email %> <%= question.updated_at.strftime(" on %m/%b/%Y") %></small></span>
            <%= if current_user == question.user then link_to t('.edit', :default => t("helpers.links.edit")), edit_question_path(question), class: "pull-right btn-xs btn-default" end%>
          </div>
        </div>


      </div>

    <% end %>

app/views/questions/show.html.erb
<%- model_class = Question -%>

<div class="panel">
  <div class="panel-heading">
    <h2><%= @question.title %></h2>
    <span> By <%= link_to @question.user.email, "#" %> on <%=@question.updated_at.strftime("%d/%b/%Y")%></span>
  </div>
  <div class="panel-body">
    <%= @question.description %>
  </div>

  <% unless @answers.nil? %>
  <hr>
  <div id="answers" class="">
    <%@answers.each do | answer |%>
    <div class="panel">
      <div class="panel-body">
        <%= answer.content %>
      </div>
      <div class="panel-footer">
        
          
          
         <span> <%= answer.user.perfil %> on <%= answer.updated_at.strftime("%d/%b/%Y")%></span>
      </div>
    </div>
    <% end%>
  </div>
  <% end%>
  <%= render partial: "form_answer"%>
</div>

<% if current_user == @question.user %>

<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_question_path(@question), :class => 'btn btn-default' %>
<% end %>