config/routes.rb
Rails.application.routes.draw do
  resources :perfil

  devise_for :users
  resources :answers
  resources :questions
  

  root to: 'questions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/perfil.rb
require 'carrierwave/orm/activerecord'

class Perfil < ApplicationRecord
  belongs_to :user
  mount_uploader :avatar, AvatarUploader

  def to_s
    return self.username
  end

  def has_avatar?
    self.avatar.length > 0 ? true : false
  end
end

app/controllers/perfil_controller.rb
class PerfilController < ApplicationController
  before_action :authenticate_user!
  before_action :set_perfil, except: [:index]

  def index
    unless current_user.perfil
      current_user.perfil = Perfil.create!({username: current_user.email.split("@").first})
    end
    
    @perfil = current_user.perfil
  end

  def edit
  end

  def create
    if  current_user.perfil.nil?
      @perfil = Perfil.new(perfil_params)

      respond_to do |format|
        if @perfil.save
          current_user.perfil = @perfil
          format.html { redirect_to @perfil, notice: 'perfil was successfully created.' }
        else
          format.html { render :new }
          format.json { render json: @perfil.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # patch 'perfil/update/:id'
  def update
      respond_to do | format |
      if @perfil.update(perfil_params)
        format.html { redirect_to '/perfil' }
      else
        format.html { render :new }
        format.json { render json: @perfil.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def set_perfil
    @perfil = Perfil.find(params[:id])
  end

  def perfil_params
    params.require(:perfil).permit(:username, :first_name, :last_name, :avatar)
  end
end

app/helpers/perfil_helper.rb
module PerfilHelper
end

app/views/perfil/edit.html.erb
<%= form_for @perfil, html:  { :class => "form-horizontal perfil" } do |f| %>
  <div class="form-group">
    <%= f.text_field :username, class: "form-input", value: @perfil.username  %>
  </div>
  <div class="form-group">
    <%= f.text_field :first_name, class: "form-input",  value: @perfil.first_name  %>
  </div>
  <div class="form-group">
    <%= f.text_field :last_name, class: "form-input",  value: @perfil.last_name  %>
  </div>
  <div class="form-group">
    <%= f.file_field :avatar, class: "form-input",  value: @perfil.avatar  %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn", value: "Update"  %>
  </div>
<% end%>

app/views/perfil/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-2">
            <img src="<%= @perfil.avatar.url%>" alt="" class="img-responsive">    
            <h3><%= @perfil.username %></h3>
                </div>
            </div>
            
            <%= link_to "Editar", edit_perfil_path(@perfil) %>
        </div>
        <div class="col-sm-4">
            <dl class="dl-vertical">        
            <dt>Primero Nome</dt>
            <dd><h5><%=  (@perfil.first_name?) ?  @perfil.first_name : (link_to "Preencher campo", edit_perfil_path( @perfil) )  %></h5></dd>
            <dt>Segundo Nome</dt>
            <dd><h5><%=  (@perfil.last_name?) ?  @perfil.last_name : ( link_to "Preencher campo", edit_perfil_path(@perfil) ) %></h5></dd>
        </dl>
        </div>
    </div>
</div>