config/routes.rb
Rails.application.routes.draw do
  resources :perfil

  devise_for :users
  resources :answers
  resources :questions
  

  root to: 'questions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Forum" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <%= link_to "Forum", root_path, class: "navbar-brand" %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          
          

        

          <ul class="nav navbar-nav navbar-right">
            <% unless current_user %>
              <li><%= link_to "Login",  new_user_session_path  %></li>
              <li><%= link_to "Registro",  new_user_registration_path  %></li>
            <% else %>
              <li> <%= link_to "Olá, #{ current_user.email}", perfil_index_path  %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete%></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <br>
    <header class="page-header">
      <%= bootstrap_flash %>

      <%if current_page?(root_path)%>
        <%= render partial: "search_form" %>
      <%end%>
    </header>
    <div class="container-fluid">
      <div class="row">
      <% unless controller.controller_name == "devise" %>
      <div class="col-sm-4">
          <h4>Categoies</h4>
          <ul class="list-group" margin="0">
            <% @categories.each do | cat |%>
              <li role="presentation" class="list-group-item"><%= link_to  cat.name.capitalize, questions_path(cat.slug) %> <span class="badge"><%=cat.question.all.count %></span> </li>
            <% end %>
          </ul>
      </div><!--/span-->
      <%end%>
        <div class="col-sm-8">

          <%= yield %>
        </div>

      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>